services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - internal-db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - internal-db
      - internal-unity

networks:
  internal-db:
  internal-unity:

volumes:
  mongo_data: